test-batchlstm: Add missing include file
Fix an compilation error:

test-batchlstm.cc: In function 'int main(int, char**)':
test-batchlstm.cc:111:27: error: 'unlink' was not declared in this scope
   unlink("__test0__.clstm");
                           ^

Signed-off-by: Stefan Weil <sw@weilnetz.de>